version: '3.6'

services:
  postgresql:
    hostname: postgresqldb
    image: postgres
    restart: always
    ports: 
      - 5432:5432
    volumes:
      - postgresql-data:/var/lib/postgresql/data
      - ./postgresql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: --encoding=UTF-8
    
volumes:
  postgresql-data:
    name: test-postgresql-data